language: python
python:
  - "2.7"
install:
    #Install conda
    - sudo pip install conda
    #install dependencies
    - sudo conda init
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - deps='pip numpy pandas requests nose'
    - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
    - export PATH=$HOME/py/bin:$PATH
script: nosetests