language: python
python:
  - "2.7"
install:
    #Install conda
    - sudo pip install conda
    #install dependencies
    - sudo conda init
    #- sudo conda update conda --yes
    - deps='pip numpy pandas requests nose'
    - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
    - export PATH=$HOME/py/bin:$PATH
script: nosetests